### ISSUE TITLE
Deprecated syntax warnings

### ISSUE THREAD

**Issue by dbrakman** [mrtzh/PrivateMultiplicativeWeights.jl#4]
I'm trying to get started using this package by running the code in examples/histograms.ipynb, but I get a number of deprecated syntax warnings:

WARNING: deprecated syntax "abstract Data" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/interface.jl:2.
Use "abstract type Data end" instead.

WARNING: deprecated syntax "abstract Query" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/interface.jl:3.
Use "abstract type Query end" instead.

WARNING: deprecated syntax "abstract Queries" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/interface.jl:4.
Use "abstract type Queries end" instead.

WARNING: deprecated syntax "typealias QueryIndex Int" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/interface.jl:7.
Use "const QueryIndex = Int" instead.

WARNING: deprecated syntax "abstract FactorHistogramQuery<:Query" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/factors.jl:19.
Use "abstract type FactorHistogramQuery<:Query end" instead.

WARNING: deprecated syntax "abstract FactorHistogramQueries<:Queries" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/factors.jl:21.
Use "abstract type FactorHistogramQueries<:Queries end" instead.

WARNING: deprecated syntax "typealias GosperState Tuple{Int64,Int64}" at /Users/me/.julia/v0.6/PrivateMultiplicativeWeights/src/gosper.jl:21.
Use "const GosperState = Tuple{Int64,Int64}" instead.

**Comment by mrtzh** [comment]
You're using Julia v0.6. Julia is changing very rapidly. The package is compatible with v0.5, but hasn't been updated to v0.6 compatibility. If you would like to make those changes, please send a pull request.

**Comment by mrtzh** [comment]
We've since updated to v1.0.
