### ISSUE TITLE
Undefined n

### ISSUE THREAD

**Issue by quatrejuin** [mrtzh/PrivateMultiplicativeWeights.jl#6]
`max(data.weights[i] + noise[i] - 1.0/(e*n*ps.epsilon), 0.0)`

At line 60 in histogram.jl,  I believe the n is undefined?

**Comment by mrtzh** [comment]
Yes you're right. It should by `num_samples` and not `n`. I believe this wasn't caught by any tests, since it's in the `noisy_init` conditional, which doesn't seem to be used much.

**Comment by mrtzh** [comment]
I just fixed it. Thanks.
