### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [mrtzh/PrivateMultiplicativeWeights.jl#9]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by mrtzh** [comment]
To be honest, the rushed transition to v1.0 was so jarring and poorly documented that I've largely given up on making this work. The last time I tried, the documentation was partially missing and what was there was confusing. The package has been ported to v1.0. It was just impossible to make it work with the Julia registry.

**Comment by KristofferC** [comment]
Sorry about that. I've made the PR https://github.com/mrtzh/PrivateMultiplicativeWeights.jl/pull/10 to start using Project files. When that is merged the simplest way to get it registered is to install the bot from https://github.com/apps/juliateam-registrator/installations/new and then comment on the merge commit of the PR with `@JuliaRegistrator register`.
